import { Button } from "@components/button/Button";
import { Meta } from "@components/meta/Meta";
import { Toggle } from "@components/toggle/Toggle";
import styles from "@styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Meta />
      <div>
        <Toggle />
        <h1>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus,
          dolore?
        </h1>
        <h2>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus,
          dolore?
        </h2>
        <h3>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus,
          dolore?
        </h3>
        <h4>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus,
          dolore?
        </h4>
        <h5>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus,
          dolore?
        </h5>
        <h6>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus,
          dolore?
        </h6>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <a href="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero,
          consectetur.
        </a>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta rerum
          perspiciatis illum magnam doloribus velit sint incidunt ipsa labore,
          eius, quasi, odit nisi ab alias culpa corporis. Quia ab est
          repellendus eum minus culpa at iste voluptatum consectetur explicabo
          inventore eos possimus, magni consequatur, laboriosam corporis. Labore
          iure quasi quisquam illum dicta esse? Doloribus, amet. Odit cupiditate
          adipisci at sed dicta dolores tenetur iure, eos quam in laboriosam
          dignissimos odio amet assumenda corporis aperiam fugiat, blanditiis
          officiis autem. A veritatis nulla nesciunt assumenda deserunt amet
          iusto commodi. Accusamus voluptatum, pariatur neque ipsa excepturi
          quis tenetur beatae earum? Reiciendis, quos placeat.
        </p>
        <img src="/128h/logo.png" alt="logo" height="128px" width="128px" />
        <img src="/192h/logo.png" alt="logo" height="192px" width="192px" />
        <img src="/512h/logo.png" alt="logo" height="512px" width="512px" />
        <Button styleType="primary">Lorem ipsum dolor sit</Button>
        <Button styleType="secondary">Lorem ipsum dolor sit</Button>
        <form>
          <select name="1" id="1">
            <option value="">Lorem</option>
            <option value="">Lorem</option>
            <option value="">Lorem</option>
            <option value="">Lorem</option>
          </select>
          <input type="text" placeholder="Lorem ipsum dolor sit amet" />
          <input type="color" />
          <input type="email" />
          <input type="date" />
          <input type="file" />
          <textarea name="2" id="2" cols={30} rows={10}></textarea>
          <button type="submit">Submit</button>
        </form>
        <ul>
          <li>
            UL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            UL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            UL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            UL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            UL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
        </ul>
        <ol>
          <li>
            OL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            OL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            OL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            OL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
          <li>
            OL Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
            possimus.
          </li>
        </ol>
      </div>
    </div>
  );
}
